[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200

; upload_protocol = espota
; upload_port = 192.168.100.33

board_build.partitions = huge_app.csv 